name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Call deploy script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd /www/wwwroot/cicd.arindoutamaperkasa.com/ && chmod 777 server_deploy.sh && ./server_deploy.sh
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
        env:
          CI: true